### ISSUE TITLE
NullPointer

### ISSUE THREAD

**Issue by Kimpka** [P24dev/deathchest#4]
https://pastebin.com/cULRWNJ1

Literally only spams it on the console.

Paper build: 118 1.15.2
Plugin version: v0.2

**Comment by P24dev** [comment]
Hi! Thanks for the report. Can i take a look at your config.yml? Thanks!

**Comment by P24dev** [comment]
Thanks for the report! The issue has been fixed, and a new jar has been uploaded. This issue will be closed.
